### ISSUE TITLE
Content for surplus card

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/buildabudget#24]
This round we won't be going deeper into funds stuff but will let people know they have a surplus and that it could go to lowering....something. 

Grace, we need some text to explain what they could do with that money. 

Below is a quick idea of the card we are working with. It will be on the report page. 
<img width="391" alt="screen shot 2016-08-06 at 10 36 38 am" src="https://cloud.githubusercontent.com/assets/10767430/17457583/dc95ad80-5bc1-11e6-9f48-168e361aff05.png">

**Comment by mateoclarke** [comment]
@graceatkins made this: https://docs.google.com/spreadsheets/d/1U4yt8Idkyk8rJCkgvSU1ijvcNOEGSOOOE1Q3BLgDl-o/edit?ts=579b9855#gid=0

**Comment by VictoriaODell** [comment]
"We're trying to work on the options for what people do with money left over: 
We can lower: 
property taxes 
utility transfers (Austin Energy/Austin Water)
Transportation User Fee

We could also just say: you have XXX amount of surplus."

**Comment by graceatkins** [comment]
potentially go towards lowering the taxes and fees collected by the city such as austin energy rates, transportation user fee, property tax bills.

**Comment by VictoriaODell** [comment]
"You have unused funds

$xx,xxx

This means could lead to lowering the taxes and fees collected by the city Such as Austin energy rates, transportation user fee, property tax bills, and more."
