### ISSUE TITLE
fix gh-pages

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/buildabudget#28]
Trying to create a `/dist` directory so I can push something up to gh-pages.

Tried `npm build`, which seems to use the `webpack.production.config` but nothing happens in my terminal. No errors, no new folders.

![screenshot](http://dsh.re/6ea09)

Tried to 👀 how `webpack.production.config` is different from `webpack.config`, but not sure.

Any suggestions @syousif94 or @luqmaan?

thx

**Comment by wilsaj** [comment]
Try `npm run build` instead?

npm scripts are generally executed as `npm run <scriptname>`, but confusingly the `start` script can be run using the shorthand `npm start` instead of `npm run start`. It's weird.

**Comment by syousif94** [comment]
@wilsaj is right, you need to do `npm run` for every command besides `start`.

If you look at the package.json, there's a command called `deploy` that's runs `build` and then a deploy script. In the instabus repo, there's a deploy script that pushes the dist directory to the gh-page branch of the current repo.

**Comment by mateoclarke** [comment]
nice, that's easy. thanks y'all.

Now I'm trying to get my `dist` files to work on gh-pages. Here is the link:
http://www.open-austin.org/hack-the-budget/

I can see my code is uglified in the js that's coming down from the server, but the React components aren't mounting to the HTML. Do y'all notice anything equally obvious as my last question?
![screenshot](http://dsh.re/db58d)

**Comment by mateoclarke** [comment]
@luqmaan helped me narrow this down to an issue with with React-Router.

There is this option, https://github.com/rafrex/spa-github-pages.

Or maybe there is another option with the new Cloudfare DNS and subdomains we can do with whatever.open-austin.org.

Also I went ahead and bought austinbudget.party because I thought it was funny.

**Comment by mateoclarke** [comment]
We're good now with React-Router's hashHistory replacing browserHistory.

Urls are ugly but we have a new issue for that... #43 

http://austinbudget.party/ is a thing 🎉
