### ISSUE TITLE
Update pretty background for Welcome page

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/buildabudget#36]
We have `home-background.png` we can use for the Welcome page.

**Comment by VictoriaODell** [comment]
![homebackground](https://cloud.githubusercontent.com/assets/10767430/17640990/2eb0f1ae-60d3-11e6-8c61-aaf9830f8e6d.png)


Will this work? It's a png.

**Comment by mateoclarke** [comment]
![](http://dsh.re/f8ad0)
