### ISSUE TITLE
discussion items for meeting Fri 8/12

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/buildabudget#39]
- [x] Rounding off numbers
_Ok to do this to the $1,000 mark?_

- [x] realtime feedback for user while incrementing amount for department
    - _show percentage change from last year?_
    - _so amount in red when it is below last year, green when more?_

- [x] Learn More
    - _print outs? can we remove this link for now?_

- [x] Domain & hosting
    - working on getting buildabudget.open-austin.org setup.
    - got delayed bc of broader DNS changes for our OA hosting.
    - I also bought `austinbudget.party` for $1.06 because I thought it was funny.

- [x] Language/Copy
    - confirm [values for department spending last year](https://docs.google.com/spreadsheets/d/1MqtWpmFJMVvEgEPVLx_dyKxkDjyiCp9CFfO3J9pwU7s/edit#gid=1498354466)
    - confirm [descriptions of service groups & individual departments](https://docs.google.com/document/d/1w8K_NCuPGsyIHlhoTU_rgC69oL7tcnieecP2kjPIFAk/edit)
    - other?

**Comment by VictoriaODell** [comment]
###For Learn More
- Have department performance reports as a print-outs to support "learn more".
- Link out "learn more" link by service groups if possibly instead of by specific departments

**Comment by graceatkins** [comment]
@mateoclarke for the descriptions. This is the correct document. Its basically the same but it has the most concise descriptions and edits. https://docs.google.com/document/d/1w8K_NCuPGsyIHlhoTU_rgC69oL7tcnieecP2kjPIFAk/edit

**Comment by mateoclarke** [comment]
| Departments | 2015-16 Budget |
| ------ | ------ |
| Municipal Courts | $21,086,564 |
| Police | $373,570,249 |
| Fire | $175,266,499 |
| Emergency Management Services | $78,255,956 |
| Planning & Zoning | $7,505,329 |
| Development Services | $32,902,297 |
| Animal Services | $11,546,362 |
| Parks & Recreation | $75,432,093 |
| Public Libraries | $41,755,192 |
| Social Service Contracts | $7,793,303 |
| Health & Human Services | $36,080,604 |
| Neighborhood Housing and Community Development | $4,818,944 |
| Transportation Department | unknown |
| Public Works | unknown |
| Watershed Protection | unknown |

@graceatkins, I'm missing last years spending on the last three departments.

**Comment by graceatkins** [comment]
Transportation: 852,536
Public works: 360,943

Watershed actually didnt get any from General Fund last year

**Comment by mateoclarke** [comment]
where did Watershed's funds come from? Might be helpful to have a sentence explaining why you are starting at $0 for that card.

**Comment by graceatkins** [comment]
Residential and commercial drainage fees. Watershed protection is included under infrastructure and mobility category but isn’t supported by the general fund (that was an oversight on my part). If its possible to exclude I would, but we can work around if its too much work because that was my fault!

**Comment by mateoclarke** [comment]
No problem, we'll drop that department card.
