### ISSUE TITLE
Overviews for Departments and Revenue Sources

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/buildabudget#5]

**Comment by graceatkins** [comment]
I think it would be helpful if we could provide a link to the overall performance website on the platform somewhere, so people can explore it if we don't provide the info they're looking for. https://data.austintexas.gov/stories/s/mfnw-2iaf

**Comment by graceatkins** [comment]
This is the doc I have started to compile department overviews

[https://docs.google.com/document/d/10vOh_fAFRKbjuYXCV_ynDoJlX9yuJP1w5ekc0OF1s8U/edit?usp=sharing(url)
