### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/buildabudget#8]
We want this app to have a friendly and approachable aesthetic. Trying to run the City is a hard and heady problem. Let's not make this hard to look at too.

- fonts & typography
- colors
- hack the budget branding ( see #9 )
- icons ( see #7 & #20 )

**Comment by mateoclarke** [comment]
Adding Icons to the list above. Here are the [icons](https://drive.google.com/folderview?id=0BwevWHqqM3MWcGNnNVNSXzE2OWM&usp=sharing) @graceatkins gathered

**Comment by brainnews** [comment]
hey @mateoclarke, I'm a recently-moved-to-austin designer and would love to help on this. Do you still have a need for these items?

**Comment by graceatkins** [comment]
Hey Miles!

We would love any and all design help we can get! I gathered some icons
over the weekend, but they're pretty basic. If you're interested in
designing others or build on the ones I created I can send you the adobe
files. Let me know what I can do to be helpful!

Grace

**Comment by VictoriaODell** [comment]
Hey @brainnews will you be at the Hack Night tomorrow? 
You can RSVP here: http://www.meetup.com/Open-Austin/events/232276549/

You should join us on slack also if you haven't already at [slack.open-austin.org](slack.open-austin.org)

**Comment by brainnews** [comment]
hey @VictoriaODell – I will be there! Excited to meet the crew.

@graceatkins – I spent a little time on the bottom bar icons ( #20 ) and, if you all are into the style, then I'd go ahead and create icons in the same style for the rest of the experience. Here is a screenshot of the icons in progress (I haven't designed the "services" icon yet).

![screen shot 2016-07-25 at 10 47 23 pm](https://cloud.githubusercontent.com/assets/3944802/17125525/cd837bc6-52b9-11e6-8536-fae26a4b8a10.jpg)

**Comment by VictoriaODell** [comment]
Thos are so awesome!

**Comment by mateoclarke** [comment]
DOPE! can't wait to include these!

**Comment by brainnews** [comment]
Sweet! Glad you like them. See you all tonight.

**Comment by graceatkins** [comment]
![turquoise](https://cloud.githubusercontent.com/assets/20227549/17457803/868fdf9a-5bc7-11e6-8aea-a43c4d3c6eb1.png)
![fffcf2-aaaaaa-f87f01-343633-70a0af](https://cloud.githubusercontent.com/assets/20227549/17457805/891bd3fe-5bc7-11e6-9e78-3f9d28ee5760.png)

**Comment by graceatkins** [comment]
![1c1c1c-e8e9f3-008dcb-ffec5c-e1315b](https://cloud.githubusercontent.com/assets/20227549/17457835/79bafb6e-5bc8-11e6-9456-3316de4ffa72.png)
